import { Sun, BookOpen, Eye, Droplet, Leaf } from "lucide-react";

export const PATHS = {
  ONBOARDING: "/onboarding",
  HOME: "/",
  LIBRARY: "/library",
  ROUTINE_PLAYER: "/routine-player",
  EYE_RELAX: "/eye-relax",
  EYE_RECOVERY_PLAYER: "/eye-recovery-player",
  HYDRATION: "/hydration",
  HYDRATION_HISTORY: "/hydration-history",
  WELLNESS_TRACKER: "/wellness-tracker",
  REMINDERS: "/reminders",
  SETTINGS: "/settings",
  HISTORY: "/history",
  RECOVERY_LIBRARY: "/recovery",
  RECOVERY_PLAYER: "/recovery-player",
  ABOUT: "/about",
  WEEKLY_REFLECTION: "/weekly-reflection",
  ACHIEVEMENTS: "/achievements",
  WELLNESS_INSIGHTS: "/wellness-insights",
  FOCUS_SESSIONS: "/focus",
  FOCUS_PLAYER: "/focus-player",
  SLEEP_WIND_DOWN: "/sleep",
  SLEEP_RITUAL_PLAYER: "/sleep-player",
  BREATHING: "/breathing",
  MOOD_JOURNAL: "/mood-journal",
  EVENING_REFLECTION: "/evening-reflection",
  GRATITUDE_GARDEN: "/gratitude-garden",
  SANCTUARY: "/sanctuary",
  WISDOM: "/wisdom",
  EMOTIONAL_WEATHER: "/emotional-weather",
  LETTERS: "/letters",
  SELF_COMPASSION: "/self-compassion",
  CALM_SOUNDS: "/calm-sounds",
  COMPANION: "/companion",
  MEMORIES: "/memories",
};

export const PAGE_TITLES = {
  ["/onboarding"]: "Welcome",
  ["/"]: "Sthira",
  ["/library"]: "Routine Library",
  ["/routine-player"]: "Routine",
  ["/eye-relax"]: "Eye Recovery",
  ["/eye-recovery-player"]: "Eye Recovery Session",
  ["/hydration"]: "Hydration",
  ["/hydration-history"]: "Hydration History",
  ["/wellness-tracker"]: "Daily Wellness",
  ["/reminders"]: "Reminders",
  ["/settings"]: "Settings",
  ["/history"]: "Completion History",
  ["/recovery"]: "Study Break Recovery",
  ["/recovery-player"]: "Recovery Session",
  ["/about"]: "About Sthira",
  ["/weekly-reflection"]: "Weekly Reflection",
  ["/achievements"]: "Achievements",
  ["/wellness-insights"]: "Wellness Insights",
  ["/focus"]: "Focus Sessions",
  ["/focus-player"]: "Focus Session",
  ["/sleep"]: "Sleep Wind-Down",
  ["/sleep-player"]: "Sleep Ritual",
  ["/breathing"]: "Mindful Breathing",
  ["/mood-journal"]: "Mood Journal",
  ["/evening-reflection"]: "Evening Reflection",
  ["/gratitude-garden"]: "Gratitude Garden",
  ["/sanctuary"]: "Digital Sanctuary",
  ["/wisdom"]: "Daily Wisdom",
  ["/emotional-weather"]: "Emotional Weather",
  ["/letters"]: "Letters to Self",
  ["/self-compassion"]: "Self-Compassion",
  ["/calm-sounds"]: "Calm Sounds",
  ["/companion"]: "Gentle Companion",
  ["/memories"]: "Memory Timeline",
};

export const NAV_ITEMS = [
  { label: "Home", path: "/", icon: Sun },
  { label: "Library", path: "/library", icon: BookOpen },
  { label: "Eyes", path: "/eye-relax", icon: Eye },
  { label: "Hydration", path: "/hydration", icon: Droplet },
  { label: "Wellness", path: "/wellness-tracker", icon: Leaf },
  // { label: "Sleep", path: "/sleep", icon: Moon },
];

export const isTopLevelPath = (pathname) =>
  NAV_ITEMS.some((item) => item.path === pathname);
